export const t = {
  pt: {
    contact: "Entrar em contato",
    developer: "Desenvolvedor",
    hero: "Desenvolvedor full stack com foco em performance, segurança e bom design. Tenho experiência prática em desenvolvimento web e mobile, utilizando tecnologias modernas para criar soluções funcionais e escaláveis.",
    viewProjects: "Ver Projetos",
    trajectory: "Trajetória",
    projects: "Projetos",
    skills: "Skills Técnicas",
    career: "Carreira",
    education: "Educação",
    devMobile: "Estágio Desenvolvedor Web",
    devStack: "Desenvolvedor de Software",
    feedbacks: "Depoimentos",
    contactFormTitle: "Tem um projeto? Vamos conversar!",
    contactFormDesc:
      "Preencha o formulário abaixo e retornarei o mais rápido possível.",
    name: "Seu nome",
    email: "Seu email",
    message: "Nos conte sobre seu projeto...",
    send: "Enviar mensagem",
  },
  en: {
    contact: "Contact me",
    developer: "Developer",
    hero: "Full stack developer focused on performance, security, and good design. I have hands-on experience in web and mobile development, using modern technologies to create functional and scalable solutions.",
    viewProjects: "View Projects",
    trajectory: "Trajectory",
    projects: "Projects",
    skills: "Technical Skills",
    career: "Career",
    education: "Education",
    devMobile: "Web Developer Intern",
    devStack: "Software Developer",
    feedbacks: "Testimonials",
    contactFormTitle: "Have a project? Let’s work together!",
    contactFormDesc:
      "Fill the form below and I’ll get back to you as soon as possible.",
    name: "Your name",
    email: "Your email",
    message: "Tell me about your project...",
    send: "Send message",
  },
};
